### ISSUE TITLE
"Unknown Error" when using with Home Assistant

### ISSUE THREAD

**Issue by bachya** [bachya/aioguardian#49]
User @arungpillai reports:

>I am unable to find any log related to the Guardian. I got Valve and HA on the same router with permanent IP, pinging from HA to Guardian works as expected. Guardian works well on the app. when i am adding using integration + Guardian add the IP and default port always says unknown error.

Home Assistant issue (closed unless Home Assistant is determined as the problem): https://github.com/home-assistant/core/issues/36728#issuecomment-643712990

**Comment by bachya** [comment]
@arungpillai, let's do some debugging with this library.

1. Clone the latest version and `cd` into it:

```bash
$ git clone https://github.com/bachya/aioguardian.git
$ cd aioguardian/
```

2. Set up and activate a Python virtual environment:

```bash
$ python3 -m virtualenv .venv
$ source .venv/bin/activate
```

3. Initialize the dev environment for ``:

```bash
$ script/setup
```

4. Open [`examples/test_client.py`](https://github.com/bachya/aioguardian/blob/dev/examples/test_client.py) in a text editor and put your Guardian unit's UP address into line 15 – once you're done, save and close the file:

```python
async with Client("<IP ADDRESS>") as guardian:
```

6. Back on the command line, run [`examples/test_client.py`](https://github.com/bachya/aioguardian/blob/dev/examples/test_client.py):

```bash
$ python3 examples/test_client.py
```

This will output some diagnostics information, as well as open and close the valve. Please report back with:

1. Any information (JSON, errors, etc.) from the command line
2. Confirmation that the valve opened and closed

Thanks!

**Comment by arungpillai** [comment]
Thanks, I am running HassOS 4.10 on Raspberry 4. Tomorrow I will install on Docker so that I run the steps that you provided.

**Comment by arungpillai** [comment]
"""Run an example script to quickly test the guardian."""
import asyncio
import logging

from aioguardian import Client
from aioguardian.errors import GuardianError

_LOGGER = logging.getLogger(__name__)


async def main() -> None:
    """Create the aiohttp session and run the example."""
    logging.basicConfig(level=logging.INFO)

    async with Client("192.168.0.61") as guardian:


--------------------------------------------------------
(awesome_venv) kichu@kichu-HP-EliteBook-8440p:~/aioguardian$ ping 192.168.0.61
PING 192.168.0.61 (192.168.0.61) 56(84) bytes of data.
64 bytes from 192.168.0.61: icmp_seq=1 ttl=255 time=98.3 ms
64 bytes from 192.168.0.61: icmp_seq=2 ttl=255 time=115 ms
64 bytes from 192.168.0.61: icmp_seq=3 ttl=255 time=34.3 ms

-----------------------------------------------------------------------------

(awesome_venv) kichu@kichu-HP-EliteBook-8440p:~/aioguardian$ python3 examples/test_client.py
INFO:aioguardian.client:sensor_pair_dump command timed out; trying again
Traceback (most recent call last):
  File "examples/test_client.py", line 105, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "examples/test_client.py", line 22, in main
    pair_dump_response = await guardian.sensor.pair_dump()
  File "/home/kichu/aioguardian/aioguardian/commands/sensor.py", line 36, in pair_dump
    return await self._execute_command(Command.sensor_pair_dump, silent=silent)
  File "/home/kichu/aioguardian/aioguardian/client.py", line 102, in _execute_command
    await self._stream.send(json.dumps(payload).encode())
  File "/home/kichu/aioguardian/awesome_venv/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 129, in send
    await super().send(data)
  File "/home/kichu/aioguardian/awesome_venv/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 91, in send
    _ = self.exception
  File "/home/kichu/aioguardian/awesome_venv/lib/python3.8/site-packages/asyncio_dgram/aio.py", line 51, in exception
    raise exc
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1009, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by bachya** [comment]
@arungpillai The `Connection refused` message indicates that your device isn't listening for requests on port 7777. Can you telnet into that port to confirm?

**Comment by arungpillai** [comment]
kichu@kichu-HP-EliteBook-8440p:~$ telnet 192.168.0.61 7777
Trying 192.168.0.61...
telnet: Unable to connect to remote host: Connection refused

any other port i should try ?

**Comment by bachya** [comment]
@arungpillai Not to my knowledge; port 7777 is what my valve controller uses. You might consider some sort of port scan of the device.

Since this is not an issue with this library, I'm going to close this issue. Please follow up if it appears that the library is at fault. Thanks!

**Comment by arungpillai** [comment]
I am using the following valve, did you use similor one for testing?

![image](https://user-images.githubusercontent.com/61244068/84907726-c8358d80-b070-11ea-8d4b-9e4b3ba6c6a0.png)

**Comment by bachya** [comment]
@arungpillai Yep, that looks like the same unit I have.
